# Generated by Django 6.0.1 on 2026-01-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysper_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TRAINEE', 'Trainee'), ('TRAINER', 'Trainer')], max_length=10)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.activity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.person')),
            ],
            options={
                'unique_together': {('person', 'activity', 'role')},
            },
        ),
    ]
