# Generated by Django 6.0.1 on 2026-01-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_rename_activity_to_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.CharField(max_length=120),
        ),
    ]
