# Generated by Django 6.0.1 on 2026-01-13 14:37

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_training_capacity_training_remarks_and_more'),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.AddField(
            model_name='participation',
            name='timespan',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=django.contrib.postgres.indexes.GistIndex(fields=["timespan"], name="participation_timespan_gist"),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('person', '='), ('timespan', '&&')], name='no_overlapping_participation_per_person'),
        ),
    ]

