# Generated by Django 6.0.1 on 2026-01-13 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_participation_timespan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameIndex(
            model_name='participation',
            new_name='training_pa_timespa_8c0d7b_gist',
            old_name='participation_timespan_gist',
        ),
        migrations.AddField(
            model_name='training',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='training.subject'),
        ),
        migrations.AddField(
            model_name='trainerskill',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.subject'),
        ),
        migrations.AddField(
            model_name='trainerskill',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.person'),
        ),
        migrations.AlterUniqueTogether(
            name='trainerskill',
            unique_together={('trainer', 'subject')},
        ),
    ]
