# Generated by Django 6.0.1 on 2026-01-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_subject_trainerskill_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='training',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='training_end_after_start'),
        ),
    ]
