# Generated by Django 6.0.1 on 2026-01-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_training_training_end_after_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
