# Generated by Django 6.0.1 on 2026-01-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_participation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
