# Generated by Django 6.0.1 on 2026-01-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_person_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='validity_days',
            field=models.PositiveIntegerField(default=365),
        ),
    ]
