# Generated by Django 6.0.1 on 2026-01-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contingent',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
