# Generated by Django 6.0.1 on 2026-01-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_person_contingent'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('AUTHORISED', 'Authorised'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=12),
        ),
    ]
