# Generated by Django 6.0.1 on 2026-01-30 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_participation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='completion_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='participation',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='participation',
            name='pos_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='participation',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participation',
            name='status_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
