# Generated by Django 6.0.1 on 2026-01-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_participation_completion_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseOfForceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('PUSH_UPS', 'Push-ups'), ('SIT_UPS', 'Sit-ups'), ('RUN_1000M', '1000m run')], max_length=20)),
                ('age_group', models.CharField(choices=[('UP_TO_29', 'up to 29 years'), ('AGE_30_34', '30-34 years'), ('AGE_35_39', '35-39 years'), ('AGE_40_44', '40-44 years'), ('AGE_45_49', '45-49 years'), ('AGE_50_54', '50-54 years'), ('AGE_55_59', '55-59 years'), ('AGE_60_PLUS', '60 and over')], max_length=20)),
                ('minimum', models.PositiveIntegerField()),
                ('good', models.PositiveIntegerField()),
                ('very_good', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['exercise', 'age_group'],
                'unique_together': {('exercise', 'age_group')},
            },
        ),
    ]
