# Generated by Django 6.0.1 on 2026-01-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_useofforcestandard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useofforcestandard',
            options={'ordering': ['exercise', 'age_sort']},
        ),
        migrations.RemoveField(
            model_name='useofforcestandard',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='useofforcestandard',
            name='age_sort',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useofforcestandard',
            name='age_group',
            field=models.CharField(choices=[('U29', 'Up to 29'), ('30_34', '30–34'), ('35_39', '35–39'), ('40_44', '40–44'), ('45_49', '45–49'), ('50_54', '50–54'), ('55_59', '55–59'), ('60_PLUS', '60 and over')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useofforcestandard',
            name='exercise',
            field=models.CharField(choices=[('PUSHUPS', 'Push-ups'), ('SITUPS', 'Sit-ups'), ('RUN', '1000m run')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useofforcestandard',
            name='good',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useofforcestandard',
            name='minimum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useofforcestandard',
            name='very_good',
            field=models.IntegerField(),
        ),
    ]
