# Generated by Django 6.0.1 on 2026-02-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_alter_useofforcestandard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useofforcestandard',
            name='age_sort',
            field=models.PositiveSmallIntegerField(default=999),
            preserve_default=False,
        ),
    ]
