# Generated by Django 6.0.1 on 2026-02-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_alter_useofforcestandard_age_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useofforcestandard',
            options={'ordering': ['gender', 'exercise', 'age_sort']},
        ),
        migrations.AlterUniqueTogether(
            name='useofforcestandard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='useofforcestandard',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('F', 'Women')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='useofforcestandard',
            name='age_sort',
            field=models.PositiveSmallIntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='useofforcestandard',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useofforcestandard',
            name='minimum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useofforcestandard',
            name='very_good',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='useofforcestandard',
            unique_together={('gender', 'exercise', 'age_group')},
        ),
    ]
