# Generated by Django 6.0.1 on 2026-02-02 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_alter_useofforcestandard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='uof_chairman',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='training',
            name='uof_instructor_1',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='training',
            name='uof_instructor_2',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='UofAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_at', models.DateField(default=django.utils.timezone.now)),
                ('pushups', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('situps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('run_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pushups_rating', models.CharField(blank=True, choices=[('FAIL', 'Fail'), ('MINIMUM', 'Minimum'), ('GOOD', 'Good'), ('VERY_GOOD', 'Very good')], default='', max_length=20)),
                ('situps_rating', models.CharField(blank=True, choices=[('FAIL', 'Fail'), ('MINIMUM', 'Minimum'), ('GOOD', 'Good'), ('VERY_GOOD', 'Very good')], default='', max_length=20)),
                ('run_rating', models.CharField(blank=True, choices=[('FAIL', 'Fail'), ('MINIMUM', 'Minimum'), ('GOOD', 'Good'), ('VERY_GOOD', 'Very good')], default='', max_length=20)),
                ('passed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uof_assessment', to='training.participation')),
            ],
        ),
    ]
