# Generated by Django 6.0.1 on 2026-02-04 22:52

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_participation_removed_at_participation_removed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participation',
            name='no_overlapping_participation_per_person',
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('removed_at__isnull', True)), expressions=[('person', '='), ('timespan', '&&')], name='no_overlapping_participation_per_person'),
        ),
    ]
