# Generated by Django 6.0.1 on 2026-02-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_remove_participation_no_overlapping_participation_per_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='uof_iteration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
