# Generated by Django 6.0.1 on 2026-02-05 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_training_uof_iteration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('ASSIGNED', 'Assigned / Authorised'), ('STATUS_CHANGE', 'Status change'), ('INFO', 'Info / Other')], default='INFO', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('status_at_send', models.CharField(blank=True, default='', max_length=12)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_email_logs', to='training.person')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_training_emails', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='training.training')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['training', 'person', 'template_type'], name='training_tr_trainin_3b2d82_idx'), models.Index(fields=['person', 'sent_at'], name='training_tr_person__450ffc_idx')],
            },
        ),
    ]
