# Generated by Django 6.0.1 on 2026-02-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_trainingemaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('PARTICIPANT', 'Participant (personalised)'), ('ADMIN', 'Admin / Group (bulk)')], default='PARTICIPANT', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
