# Generated by Django 6.0.1 on 2026-02-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailRecipientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipients', models.ManyToManyField(blank=True, related_name='groups', to='training.emailrecipient')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
