# Generated by Django 6.0.1 on 2026-02-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_emailrecipient_emailrecipientgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='kind',
            field=models.CharField(choices=[('PARTICIPANT', 'Participant'), ('ADMIN', 'Admin / Academy')], db_index=True, default='PARTICIPANT', max_length=20),
        ),
    ]
