# Generated by Django 6.0.1 on 2026-02-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_alter_emailtemplate_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingemaillog',
            name='template_type',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('STATUS_CHANGE', 'Status change'), ('ADMIN_SUMMARY', 'Admin summary')], default='INFO', max_length=20),
        ),
    ]
