# Generated by Django 6.0.1 on 2026-02-07 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_alter_trainingemaillog_template_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingemaillog',
            name='external_recipient_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='trainingemaillog',
            name='external_recipient_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='trainingemaillog',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_email_logs', to='training.person'),
        ),
        migrations.AlterField(
            model_name='trainingemaillog',
            name='template_type',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('STATUS_CHANGE', 'Status change'), ('ADMIN_SUMMARY', 'Admin summary')], default='ASSIGNED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='trainingemaillog',
            index=models.Index(fields=['training', 'external_recipient_email', 'template_type'], name='training_tr_trainin_022cc2_idx'),
        ),
    ]
