# Generated by Django 6.0.1 on 2026-02-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_trainingemaillog_external_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingemaillog',
            name='delivery_status',
            field=models.CharField(choices=[('LOGGED', 'Logged'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='LOGGED', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingemaillog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingemaillog',
            name='sent_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
